version: '3'
services:
  web:
    container_name: geoapp
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/rails
    command: "./bin/rails server -b 0.0.0.0"
    depends_on:
      - db
    environment:
      - RAILS_ENV=${RAILS_ENV}
      - DATABASE_URL=${DATABASE_URL}
      - IPSTACK_API_KEY=${IPSTACK_API_KEY}
  db:
    container_name: postgres_db
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command:
      "postgres -c max_connections=500"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    
volumes:
  postgres_data:
